### ISSUE TITLE
Screen Adaptation Bug

### ISSUE THREAD

**Issue by ghost** [ollelogdahl/ConsoleGameEngine#2]
Hello, I haven't read the source code in detail yet, but the ExampleGame has a screen adaptation problem on my Windows 10 console.
![bug](https://user-images.githubusercontent.com/44442056/49417781-244ffe00-f7ba-11e8-95a9-2a5bc7ce08d5.png)

**Comment by ollelogdahl** [comment]
I'll have a look at it. Is this the original code for the Tetris example or have you done any modifications?

**Comment by ghost** [comment]
> I'll have a look at it. Is this the original code for the Tetris example or have you done any modifications?

I haven't modify any code.

**Comment by ollelogdahl** [comment]
Ok. I'll have a look at it. I have ran it on 2 windows 10 machines, worked well for both. Try the latest release, I modified some of the window drawing stuff, might work better!

**Comment by ghost** [comment]
> Ok. I'll have a look at it. I have ran it on 2 windows 10 machines, worked well for both. Try the latest release, I modified some of the window drawing stuff, might work better!

Sorry, I still can't run the lastest release normally on my machine. Maybe you should set the window size first.

![image](https://user-images.githubusercontent.com/44442056/49645885-626a4d80-fa58-11e8-88fd-d0e4ffadfca6.png)

**Comment by ollelogdahl** [comment]
@ProcessCA Thank you for the trace, I'm pretty sure why this is happening. I'll have a look at it in some hours and fix it asap! A big fail on my part

**Comment by ollelogdahl** [comment]
> Sorry, I still can't run the lastest release normally on my machine. Maybe you should set the window size first.
> 
> ![image](https://user-images.githubusercontent.com/44442056/49645885-626a4d80-fa58-11e8-88fd-d0e4ffadfca6.png)

Alright, I have now fixed the error, got it working on another computer! Hopefully it works now, sorry for the inconvenience!

**Comment by ghost** [comment]
Thank you guys. Next I'm going to study your library :)
