### ISSUE TITLE
No == and != operators for Point struct

### ISSUE THREAD

**Issue by lamierus** [ollelogdahl/ConsoleGameEngine#6]
I think it may be helpful to have the == and != for the Point struct, for comparisons.  Just adding in the following to the Point.cs may help with that, instead of having to compare the x and the y separately each time:

```
public static bool operator ==(Point lhs, Point rhs) {
    return ((lhs.X == rhs.X) && (lhs.Y == rhs.Y));
}
public static bool operator !=(Point lhs, Point rhs) {
    return ((lhs.X != rhs.X) || (lhs.Y != rhs.Y));
}
public override bool Equals(object obj) {
    return Equals(obj);
}
public override int GetHashCode() {
    return GetHashCode();
}
```

**Comment by ollelogdahl** [comment]
Absolutely, didn't put enough effort in those structs. Will rework it when i get home!
